---
level: middle
tags:
  - leetcode
linkToTask: https://leetcode.com/problems/promise-time-limit/?envType=study-plan-v2&envId=30-days-of-javascript
linkToIndex:
  - "[[JS]]"
topics:
  - js
---
## Description

Нужно написать функцию, которая на вход принимает функцию `fn` и время `t` в миллисекундах. Возвращает ограниченную по времени версию входной функции (`TLFunction`). `fn` принимает аргументы и прокидывает их `TLFunction`.

`TLFunction` функция следует правилам ниже:
1. Если функция `fn` завершится в пределах срока `t`, то `TLFunction` резолвится с этим результатом;
2. Если выполнение функции `fn` превышает ограничение по времени, то `TLFunction` реджектится со строкой `"Time Limit Exceeded"`.

---
## Constraints

- `0 <= inputs.length <= 10`
- `0 <= t <= 1000`
- `fn` returns a promise

---
## Example 1

### Input

```
fn = async (n) => { 
  await new Promise(res => setTimeout(res, 100)); 
  return n * n; 
}
inputs = [5]
t = 50
```
### Output

```
{"rejected":"Time Limit Exceeded","time":50}
```
### Explanation

```
const limited = timeLimit(fn, t)
const start = performance.now()
let result;
try {
   const res = await limited(...inputs)
   result = {"resolved": res, "time": Math.floor(performance.now() - start)};
} catch (err) {
   result = {"rejected": err, "time": Math.floor(performance.now() - start)};
}
console.log(result) // Output

The provided function is set to resolve after 100ms. However, the time limit is set to 50ms. It rejects at t=50ms because the time limit was reached.
```

---
## Example 2

### Input

```
fn = async (n) => { 
  await new Promise(res => setTimeout(res, 100)); 
  return n * n; 
}
inputs = [5]
t = 150
```
### Output

```
{"resolved":25,"time":100}
```
### Explanation

```
The function resolved 5 * 5 = 25 at t=100ms. The time limit is never reached.
```

---
## Example 3

### Input

```
fn = async (a, b) => { 
  await new Promise(res => setTimeout(res, 120)); 
  return a + b; 
}
inputs = [5,10]
t = 150
```
### Output

```
{"resolved":15,"time":120}
```
### Explanation

```
​​​​The function resolved 5 + 10 = 15 at t=120ms. The time limit is never reached.
```

---
## Answers

### Answer 1

Это решение первое, что пришло в голову, и как-то образом оно прошло через тесты. Здесь вызывают вопросы много чего и `setInterval`, который каждую единицу времени проверяет не превышен ли лимит, и отслеживание времени исполнения функции с последующей его проверкой. 

```typescript
type Callback = (...params: any[]) => Promise<any>;

function timeLimit(callback: Callback, timeLimit: number): Callback {
  return function (...args) {
    const timeStart = Date.now();

    return new Promise((resolve, reject) => {
      const timerId = setInterval(() => {
        const timeEnd = Date.now() - timeStart;

        if (timeEnd > timeLimit) {
          clearInterval(timerId);
          reject('Time Limit Exceeded');
        }
      }, 10);

      callback(...args)
        .then(data => resolve(data))
        .catch((error) => reject(error));
    });
  };
}
```

---
### Answer 2

Данное решение уже поэлегантнее. Тут как и в предыдущем есть 2 `reject`, один нужен для генерации ошибки `'Time Limit Exceeded'`, а второй, чтобы сгенерировать ошибку, которую поймал `catch` из `callback`. Без `catch` приложение просто упадет.

```typescript
type Callback = (...params: any[]) => Promise<any>;

function timeLimit(callback: Callback, timeLimit: number): Callback {
  return function (...args) {
    return new Promise(async (resolve, reject) => {
        const timerId = setTimeout(() => {
            reject('Time Limit Exceeded');
        }, timeLimit);

        try {
            resolve(await callback(...args));
        } catch (error) {
            reject(error);
        } finally {
            clearTimeout(timeLimit)
        }
    });
  };
}```

---
### Answer 3

Лучшее решение и по чистоте кода и по задумке. Вернется первый промис, который выполнится, либо оригинальной с результатом или ошибкой, либо промис с сообщением `'Time Limit Exceeded'`.

```typescript
type Callback = (...params: any[]) => Promise<any>;

function timeLimit(callback: Callback, timeLimit: number): Callback {
  return function (...args) {
      const originalPromise = callback(...args);
      const timeoutPromise = new Promise((_, reject) => {
          setTimeout(() => {
              reject('Time Limit Exceeded');
          }, timeLimit);
      });

      return Promise.race([originalPromise, timeoutPromise]);
  };
}
```