---
level: elementary
tags:
  - leetcode
linkToTask: https://leetcode.com/problems/execute-asynchronous-functions-in-parallel/description/?envType=study-plan-v2&envId=30-days-of-javascript
linkToIndex: "[[Studying on leetcode]]"
---
## Description

Дается массив асинхронных функций `functions`, нужно вернуть новый промис `promise`. Каждая функция внутри массива не принимает аргументов и возвращает промис. Все промисы должны быть выполнены в параллели.

`promise` выполняется успешно:
1. Когда все промисы, возвращенные из `functions` были успешно завершены. Успешное значение из `promise` это массив результатов в том порядке, в котором выполнились функции из `functions`.

`promise` отклоняет результат:
1. Когда любой из промисов, возвращенный из `functions` был отклонен. `promise` должен быть отклонен с причиной отклонения первого отклонения промиса.

Решить без использования `Promise.all`.

---
## Constraints

- `functions` is an array of functions that returns promises
- `1 <= functions.length <= 10`

---
## Example 1

### Input

```
functions = [
  () => new Promise(resolve => setTimeout(() => resolve(5), 200))
]
```
### Output

```
{"t": 200, "resolved": [5]}
```
### Explanation

```
promiseAll(functions).then(console.log); // [5]

The single function was resolved at 200ms with a value of 5.
```

---
## Example 2

### Input

```
functions = [
    () => new Promise(resolve => setTimeout(() => resolve(1), 200)), 
    () => new Promise((resolve, reject) => setTimeout(() => reject("Error"), 100))
]
```
### Output

```
{"t": 100, "rejected": "Error"}
```
### Explanation

```
Since one of the promises rejected, the returned promise also rejected with the same error at the same time.
```

---
## Example 3

### Input

```
functions = [
    () => new Promise(resolve => setTimeout(() => resolve(4), 50)), 
    () => new Promise(resolve => setTimeout(() => resolve(10), 150)), 
    () => new Promise(resolve => setTimeout(() => resolve(16), 100))
]
```
### Output

```
{"t": 150, "resolved": [4, 10, 16]}
```
### Explanation

```
All the promises resolved with a value. The returned promise resolved when the last promise resolved.
```

---
## Answers

### Answer 1

```typescript
type Fn<T> = () => Promise<T>

const promiseAll = <T>(functions: Fn<T>[]): Promise<T[]> => {
    const results = [];
    let countOfExecuted = 0;

    return new Promise((resolve, reject) => {
        functions.forEach(async (callback, index) => {
            try {
                const data = await callback();

                results[index] = data;

                countOfExecuted += 1;

                if (countOfExecuted === functions.length) {
                    resolve(results);
                }
            } catch (error) {
                reject(error)
            }
        });
    });
};
```

Сложность по времени: `O(n)`, потому что `forEach` выполняется за `n` времени.

Сложность по памяти: `O(n)`, потому что есть массив `results` длиной `n` .

